package com.devflow.audit.entity;

public enum AuditAction {
    USER_CREATED,
    USER_UPDATED,
    USER_LOGGED_IN,
    PROJECT_CREATED,
    PROJECT_UPDATED,
    PROJECT_DELETED,
    MEMBER_ADDED,
    MEMBER_REMOVED,
    MEMBER_ROLE_CHANGED,
    ISSUE_CREATED,
    ISSUE_UPDATED,
    ISSUE_DELETED,
    COMMENT_CREATED,
    COMMENT_DELETED,
    ENVIRONMENT_CREATED,
    ENVIRONMENT_DELETED,
    DEPLOYMENT_CREATED,
    DEPLOYMENT_STARTED,
    DEPLOYMENT_SUCCEEDED,
    DEPLOYMENT_FAILED,
    DEPLOYMENT_CANCELLED,
    API_KEY_CREATED,
    API_KEY_REVOKED
}
